# Generated by Django 5.2 on 2025-06-10 03:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Consola',
            fields=[
                ('idConsola', models.AutoField(primary_key=True, serialize=False)),
                ('nombreConsola', models.CharField(max_length=100)),
                ('marcaConsola', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Descripcion',
            fields=[
                ('idDescripcion', models.IntegerField(default=None, primary_key=True, serialize=False)),
                ('detallesDescripcion', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Distribucion',
            fields=[
                ('idDistribucion', models.IntegerField(default=None, primary_key=True, serialize=False)),
                ('localidadDistribucion', models.CharField(max_length=80)),
                ('siglaDistribucion', models.CharField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('idEstado', models.IntegerField(default=None, primary_key=True, serialize=False)),
                ('nombreEstado', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Ubicacion',
            fields=[
                ('idUbicacion', models.AutoField(primary_key=True, serialize=False)),
                ('nombreUbicacion', models.CharField(max_length=100)),
                ('descripcionUbicacion', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Clasificacion',
            fields=[
                ('idClasificacion', models.IntegerField(default=None, primary_key=True, serialize=False)),
                ('descripcionClasificacion', models.CharField(max_length=10)),
                ('distribucion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sistemas.distribucion')),
            ],
        ),
        migrations.CreateModel(
            name='Juego',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigoDeBarra', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('nombreJuego', models.CharField(max_length=250)),
                ('imagen', models.URLField(blank=True, max_length=500, null=True)),
                ('clasificacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sistemas.clasificacion')),
                ('consola', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sistemas.consola')),
                ('descripcion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sistemas.descripcion')),
                ('distribucion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sistemas.distribucion')),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sistemas.estado')),
            ],
        ),
        migrations.CreateModel(
            name='Personal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=15)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('rol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sistemas.rol')),
            ],
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('idStock', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad', models.IntegerField(default=0)),
                ('juego', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sistemas.juego')),
                ('ubicacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sistemas.ubicacion')),
            ],
            options={
                'unique_together': {('juego', 'ubicacion')},
            },
        ),
    ]
