# Generated by Django 5.2 on 2025-06-15 02:46

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistemas', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='stock',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='stock',
            name='juego',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stocks', to='sistemas.juego'),
        ),
        migrations.CreateModel(
            name='CambioJuego',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now)),
                ('campo_modificado', models.CharField(max_length=100)),
                ('valor_anterior', models.TextField()),
                ('valor_nuevo', models.TextField()),
                ('juego', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sistemas.juego')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sistemas.personal')),
            ],
        ),
        migrations.CreateModel(
            name='MovimientoStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_movimiento', models.CharField(choices=[('ENTRADA', 'Entrada'), ('SALIDA', 'Salida')], max_length=7)),
                ('cantidad', models.IntegerField()),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now)),
                ('observacion', models.TextField(blank=True, null=True)),
                ('juego', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sistemas.juego')),
                ('ubicacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sistemas.ubicacion')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sistemas.personal')),
            ],
        ),
    ]
