# Generated by Django 5.2 on 2025-05-30 19:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistemas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Descripcion',
            fields=[
                ('idDescripcion', models.IntegerField(default=None, primary_key=True, serialize=False)),
                ('detallesDescripcion', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='juego',
            name='descripcion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sistemas.descripcion'),
        ),
    ]
