# Generated by Django 5.2 on 2025-05-06 17:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistemas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Consola',
            fields=[
                ('idConsola', models.IntegerField(default=None, primary_key=True, serialize=False)),
                ('nombreConsola', models.CharField(max_length=100)),
                ('marcaConsola', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Distribucion',
            fields=[
                ('idDistribucion', models.IntegerField(default=None, primary_key=True, serialize=False)),
                ('localidadDistribucion', models.CharField(max_length=80)),
                ('siglaDistribucion', models.CharField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('idEstado', models.IntegerField(default=None, primary_key=True, serialize=False)),
                ('nombreEstado', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('idStock', models.IntegerField(default=None, primary_key=True, serialize=False)),
                ('ubicacion', models.CharField(max_length=100)),
                ('cantidad', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Ubicacion',
            fields=[
                ('idUbicacion', models.IntegerField(default=None, primary_key=True, serialize=False)),
                ('nombreUbicacion', models.CharField(max_length=100)),
                ('descripcionUbicacion', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Clasificacion',
            fields=[
                ('idClasificacion', models.IntegerField(default=None, primary_key=True, serialize=False)),
                ('descripcionClasificacion', models.CharField(max_length=10)),
                ('Distribucion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sistemas.distribucion')),
            ],
        ),
        migrations.CreateModel(
            name='Juego',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigoDeBarra', models.IntegerField(blank=True, null=True, unique=True)),
                ('nombreJuego', models.CharField(max_length=250)),
                ('imagen', models.ImageField(upload_to='juegos/')),
                ('clasificacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sistemas.clasificacion')),
                ('consola', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sistemas.consola')),
                ('distribucion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sistemas.distribucion')),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sistemas.estado')),
                ('unidades', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sistemas.stock')),
                ('ubicacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sistemas.ubicacion')),
            ],
        ),
    ]
