# Generated by Django 5.2 on 2025-06-15 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistemas', '0002_alter_stock_unique_together_alter_stock_juego_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='juego',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='juego',
            name='fecha_desactivacion',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
