# Generated by Django 5.2 on 2025-06-01 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistemas', '0002_descripcion_juego_descripcion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='cantidad',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='stock',
            name='idStock',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterUniqueTogether(
            name='stock',
            unique_together={('juego', 'ubicacion')},
        ),
    ]
