# Generated by Django 5.2 on 2025-06-03 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistemas', '0003_alter_stock_cantidad_alter_stock_idstock_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='juego',
            name='imagen',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
