# Generated by Django 5.1.7 on 2025-06-16 05:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistemas', '0005_alter_juego_imagen'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlertaStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField()),
                ('creada_en', models.DateTimeField(auto_now_add=True)),
                ('juego', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='sistemas.juego')),
            ],
        ),
    ]
