# Generated by Django 5.2 on 2025-06-17 04:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sistemas', '0006_alertastock'),
        ('sistemas', '0007_devolucion'),
    ]

    operations = [
    ]
