# Generated by Django 5.2 on 2025-06-17 04:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistemas', '0008_merge_0006_alertastock_0007_devolucion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devolucion',
            name='cantidad',
            field=models.PositiveIntegerField(verbose_name='Unidades a devolver'),
        ),
        migrations.AlterField(
            model_name='devolucion',
            name='juego',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sistemas.juego', verbose_name='Juego a devolver'),
        ),
        migrations.AlterField(
            model_name='devolucion',
            name='motivo',
            field=models.TextField(blank=True, help_text='Razón de la devolución', null=True, verbose_name='Motivo (opcional)'),
        ),
        migrations.AlterField(
            model_name='devolucion',
            name='ubicacion_destino',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sistemas.ubicacion', verbose_name='Ubicación destino'),
        ),
        migrations.AlterField(
            model_name='devolucion',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sistemas.personal', verbose_name='Registrado por'),
        ),
        migrations.AlterField(
            model_name='juego',
            name='stock_al_descontinuar',
            field=models.IntegerField(default=0, help_text='Cantidad de unidades que tenía cuando se descontinuó', null=True, verbose_name='Stock al descontinuar'),
        ),
    ]
