# Generated by Django 5.2 on 2025-06-17 05:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sistemas', '0009_alter_devolucion_cantidad_alter_devolucion_juego_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='juego',
            name='fecha_descontinuado',
        ),
        migrations.RemoveField(
            model_name='juego',
            name='stock_al_descontinuar',
        ),
    ]
