# Generated by Django 5.2 on 2025-11-07 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistemas', '0010_remove_juego_fecha_descontinuado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimientostock',
            name='tipo_movimiento',
            field=models.CharField(choices=[('ENTRADA', 'Entrada'), ('SALIDA', 'Salida'), ('DEVOLUC', 'Devolución')], max_length=10),
        ),
    ]
