# Generated by Django 5.2 on 2025-11-07 12:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistemas', '0011_alter_movimientostock_tipo_movimiento'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='personal',
            options={'verbose_name': 'Personal', 'verbose_name_plural': 'Personal'},
        ),
        migrations.AlterModelOptions(
            name='rol',
            options={'verbose_name': 'Rol', 'verbose_name_plural': 'Roles'},
        ),
        migrations.AlterField(
            model_name='personal',
            name='nombre',
            field=models.CharField(max_length=100, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='personal',
            name='rol',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sistemas.rol', verbose_name='Rol asignado'),
        ),
        migrations.AlterField(
            model_name='personal',
            name='telefono',
            field=models.CharField(max_length=15, verbose_name='Teléfono'),
        ),
        migrations.AlterField(
            model_name='personal',
            name='usuario',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario del sistema'),
        ),
        migrations.AlterField(
            model_name='rol',
            name='rol',
            field=models.CharField(max_length=50, verbose_name='Nombre del Rol'),
        ),
    ]
